pipeline {
    agent any

    stages {
        stage('Unite Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
