pipeline {
    agent any

    stages {
        stage('Unite Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-e HOME=/tmp -e GOCACHE=/tmp/go-cache'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
